version: '3.7'
services:
  xnat-web:
    build:
      context: ./xnat
    ports:
      - 8104:8104
    volumes:
      - ./.xnat/xnat/plugins:${XNAT_HOME}/plugins
      - ./.xnat/xnat/config:${XNAT_HOME}/config
      - ./.xnat/xnat-data/home/logs:${XNAT_HOME}/logs
      - ./.xnat/xnat-data/archive:${XNAT_ROOT}/archive
      - ./.xnat/xnat-data/build:${XNAT_ROOT}/build
      - ./.xnat/xnat-data/cache:${XNAT_ROOT}/cache
    depends_on:
      - xnat-db
    environment:
      - CATALINA_OPTS=-Xms${XNAT_MIN_HEAP} -Xmx${XNAT_MAX_HEAP} -Dxnat.home=${XNAT_HOME}
      - XNAT_HOME=${XNAT_HOME}
      - XNAT_DATASOURCE_DRIVER=${XNAT_DATASOURCE_DRIVER}
      - XNAT_DATASOURCE_URL=${XNAT_DATASOURCE_URL}
      - XNAT_DATASOURCE_USERNAME=${XNAT_DATASOURCE_USERNAME}
      - XNAT_DATASOURCE_PASSWORD=${XNAT_DATASOURCE_PASSWORD}
      - XNAT_DATASOURCE_HOST=xnat-db
      - XNAT_DATASOURCE_DBNAME=xnat
      - TOMCAT_XNAT_FOLDER=${TOMCAT_XNAT_FOLDER}
      - XNAT_EMAIL=${XNAT_EMAIL}
  xnat-db:
    image: postgres:${PG_VERSION}
    expose:
      - "5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./postgres:/docker-entrypoint-initdb.d 
    environment:
      - POSTGRES_PASSWORD=${XNAT_DATASOURCE_ADMIN_PASSWORD}
      - POSTGRES_DB=${XNAT_DATASOURCE_NAME}
      # variables for the sql script
      - XNAT_DATASOURCE_USERNAME=${XNAT_DATASOURCE_USERNAME}
      - XNAT_DATASOURCE_PASSWORD=${XNAT_DATASOURCE_PASSWORD}
  xnat-nginx:
    image: nginx:${NGINX_VERSION}
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    expose:
      - "80"
    depends_on:
      - xnat-web
    links:
      - xnat-web